#!/usr/bin/env bun
/**
 * Deterministic PHP fixture generator for the refactoring-toolkit demo.
 *
 * Writes fixtures/php-sample/** from fixed inline templates. The output is a
 * small PHP invoicing/catalog module (namespace `Acme\Billing`) deliberately
 * seeded with dynamic PHP idioms — associative arrays as pseudo-objects,
 * scalar coercions, late static binding, magic methods, loose comparison,
 * by-reference iteration, duck typing — and with docblocks that contradict
 * behavior in places. The per-symbol analysis and the adversarial reviewers
 * are expected to catch those; the port must not trust docblocks blindly.
 *
 * Determinism contract:
 *   - no randomness, no clock, no environment reads;
 *   - fixed file order, LF endings, exactly one trailing newline per file;
 *   - two consecutive runs are byte-identical (compare the printed DIGEST).
 *
 * Run:  bun run fixtures/generate.ts [--out <dir>]
 *       (or: npx tsx fixtures/generate.ts [--out <dir>])
 *
 * Standalone by design: zero imports beyond node: builtins, so this script
 * does not depend on the repo's package.json, tsconfig, or node_modules.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/** Marker file every generated tree carries; `main()` only wipes trees that have it. */
const MARKER = "GENERATED.txt";

/**
 * Output directory: `--out <dir>` (used by tests to regenerate into a temp
 * dir) or the committed fixtures/php-sample.
 */
function resolveOutRoot(): string {
  const i = process.argv.indexOf("--out");
  if (i < 0) return join(here, "php-sample");
  const value = process.argv[i + 1];
  if (value === undefined || value === "" || value.startsWith("--")) {
    throw new Error("--out requires a directory argument");
  }
  return resolve(value);
}

/**
 * Clears the output directory before regeneration. A missing or empty
 * directory is fine; a non-empty one must carry GENERATED.txt, so a stray
 * `--out <dir>` can never wipe a directory this generator does not own.
 */
function clearOutRoot(dir: string): void {
  if (existsSync(dir)) {
    const entries = readdirSync(dir);
    if (entries.length > 0 && !entries.includes(MARKER)) {
      throw new Error(`refusing to wipe ${dir}: it is not empty and has no ${MARKER} marker`);
    }
  }
  rmSync(dir, { recursive: true, force: true });
}

const outRoot = resolveOutRoot();

type FixtureFile = { readonly path: string; readonly content: string };

const FILES: FixtureFile[] = [
  {
    path: "GENERATED.txt",
    content: `
Directory generated by fixtures/generate.ts (deterministic fixture generator).

Do not edit files under php-sample/ by hand. Edit fixtures/generate.ts and re-run:

    bun run fixtures/generate.ts        # or: npx tsx fixtures/generate.ts

Two consecutive runs produce byte-identical output (no randomness, no clock).
`,
  },
  {
    path: "src/Support/Arrayable.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Support;

interface Arrayable
{
    /**
     * @return array<string, mixed>
     */
    public function toArray();
}
`,
  },
  {
    path: "src/Support/Taggable.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Support;

/**
 * Reusable tag bookkeeping.
 *
 * Tags are always flat strings once stored, and merging is only meaningful
 * between entities of the same class.
 */
trait Taggable
{
    /** @var array<int, string> */
    private $tags = [];

    public function addTag($tag)
    {
        $this->tags[] = (string) $tag;

        return $this;
    }

    public function addTags(...$tags)
    {
        foreach ($tags as $tag) {
            $this->addTag($tag);
        }

        return $this;
    }

    /**
     * @return array<int, string>
     */
    public function tags()
    {
        return $this->tags;
    }

    public function hasTag($tag)
    {
        return in_array((string) $tag, $this->tags, true);
    }

    /**
     * Merges tags from another entity, which must expose tags().
     */
    public function mergeTagsFrom($other)
    {
        foreach ($other->tags() as $tag) {
            if (!$this->hasTag($tag)) {
                $this->addTag($tag);
            }
        }

        return $this;
    }
}
`,
  },
  {
    path: "src/Money.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing;

/**
 * Immutable monetary value in a single currency.
 *
 * Amounts are stored as floats in the major currency unit and are always
 * non-negative.
 */
final class Money
{
    public const DEFAULT_CURRENCY = 'USD';

    /** @var float */
    private $amount;

    /** @var string */
    private $currency;

    public function __construct($amount, $currency = self::DEFAULT_CURRENCY)
    {
        $this->amount = (float) $amount;
        $this->currency = (string) $currency;
    }

    /**
     * Named constructor for messy human input such as "1,234.50" or " 12 ".
     */
    public static function parse($raw, $currency = self::DEFAULT_CURRENCY)
    {
        $normalized = str_replace([' ', ','], '', (string) $raw);
        if ($normalized === '') {
            return new self(0, $currency);
        }

        return new self((float) $normalized, $currency);
    }

    public function amount()
    {
        return $this->amount;
    }

    public function currency()
    {
        return $this->currency;
    }

    public function add(Money $other)
    {
        $this->assertSameCurrency($other);

        return new self($this->amount + $other->amount, $this->currency);
    }

    public function subtract(Money $other)
    {
        $this->assertSameCurrency($other);

        return new self($this->amount - $other->amount, $this->currency);
    }

    public function multiply($factor)
    {
        // Operator coercion: numeric strings such as "2.5" are valid factors.
        return new self($this->amount * $factor, $this->currency);
    }

    /**
     * A percentage of this amount, rounded to 2 decimals.
     */
    public function percentage($percent)
    {
        $raw = $this->amount * ((float) $percent) / 100;

        return new self(round($raw, 2), $this->currency);
    }

    public function equals($other)
    {
        return $other instanceof self
            && $this->amount == $other->amount // loose compare on purpose
            && $this->currency === $other->currency;
    }

    public function isNegative()
    {
        return $this->amount < 0;
    }

    private function assertSameCurrency(Money $other)
    {
        if ($this->currency !== $other->currency) {
            throw new \InvalidArgumentException(sprintf(
                'Currency mismatch: %s vs %s',
                $this->currency,
                $other->currency
            ));
        }
    }

    public function __toString()
    {
        return sprintf('%.2f %s', $this->amount, $this->currency);
    }
}
`,
  },
  {
    path: "src/Customer.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing;

/**
 * A billing customer hydrated from storage rows.
 *
 * Storage rows are plain associative arrays; unknown keys are preserved and
 * reachable through the magic property accessors.
 */
final class Customer
{
    /** @var array<string, mixed> */
    private $attributes;

    public function __construct(array $attributes = [])
    {
        $defaults = [
            'id' => null,
            'name' => '',
            'email' => null,
            'vat_number' => null,
            'credit_limit' => '0.00',
        ];

        $this->attributes = array_merge($defaults, $attributes);
    }

    public static function fromArray(array $row)
    {
        return new self($row);
    }

    public function id()
    {
        return $this->attributes['id'];
    }

    public function name()
    {
        return $this->attributes['name'];
    }

    /**
     * Credit limit is stored as a numeric string. Returns null when the
     * customer has no limit configured.
     */
    public function creditLimit()
    {
        $limit = $this->attributes['credit_limit'];

        return $limit === null ? null : Money::parse($limit);
    }

    public function hasCreditFor(Money $requested)
    {
        $limit = $this->creditLimit();
        if ($limit === null) {
            return true;
        }

        return $limit->amount() >= $requested->amount();
    }

    public function __get($name)
    {
        if (array_key_exists($name, $this->attributes)) {
            return $this->attributes[$name];
        }

        trigger_error(sprintf('Undefined property: Customer::$%s', $name), E_USER_NOTICE);

        return null;
    }

    public function __isset($name)
    {
        return isset($this->attributes[$name]);
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray()
    {
        return $this->attributes;
    }
}
`,
  },
  {
    path: "src/Product.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing;

use Acme\Billing\Pricing\DiscountPolicy;
use Acme\Billing\Support\Arrayable;
use Acme\Billing\Support\Taggable;

/**
 * A catalog product.
 */
final class Product implements Arrayable
{
    use Taggable;

    /** @var string */
    private $sku;

    /** @var string */
    private $name;

    /**
     * Unit price in cents. Prices are always integers in cents.
     */
    private $priceCents;

    /** @var string */
    private $currency;

    /** @var array<string, mixed>|null */
    private $metadata;

    public function __construct($sku, $name, $priceCents, $metadata = null, $currency = Money::DEFAULT_CURRENCY)
    {
        $this->sku = (string) $sku;
        $this->name = (string) $name;
        $this->priceCents = $priceCents;
        $this->currency = (string) $currency;
        $this->metadata = $metadata;
    }

    /**
     * Hydrates from a raw catalog row. Missing keys fall back to
     * sku='', name='', price_cents=0.
     */
    public static function fromArray(array $row)
    {
        $product = new self(
            $row['sku'] ?? '',
            $row['name'] ?? '',
            $row['price_cents'] ?? 0,
            $row['metadata'] ?? null,
            $row['currency'] ?? Money::DEFAULT_CURRENCY
        );

        foreach ((array) ($row['tags'] ?? []) as $tag) {
            $product->addTag($tag);
        }

        return $product;
    }

    public function sku()
    {
        return $this->sku;
    }

    public function name()
    {
        return $this->name;
    }

    public function currency()
    {
        return $this->currency;
    }

    public function metadata()
    {
        return $this->metadata;
    }

    /**
     * Unit price as a Money value in the product's currency.
     */
    public function price()
    {
        return new Money($this->priceCents / 100, $this->currency);
    }

    /**
     * True when this product costs strictly less than $other, which may be a
     * Product or a raw catalog row array.
     */
    public function cheaperThan($other)
    {
        if (is_array($other)) {
            $otherPrice = $other['price_cents'];
        } else {
            $otherPrice = $other->priceCents;
        }

        return $this->priceCents < $otherPrice;
    }

    public function discountedPrice(DiscountPolicy $policy, $units = 1)
    {
        return $policy->apply($this->price(), $units);
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray()
    {
        return [
            'sku' => $this->sku,
            'name' => $this->name,
            'price_cents' => $this->priceCents,
            'currency' => $this->currency,
            'tags' => $this->tags(),
            'metadata' => $this->metadata,
        ];
    }
}
`,
  },
  {
    path: "src/Pricing/DiscountPolicy.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Pricing;

use Acme\Billing\Money;

interface DiscountPolicy
{
    /**
     * Applies this policy to a subtotal for the given number of units.
     *
     * @param Money $subtotal
     * @param int   $units
     *
     * @return Money
     */
    public function apply(Money $subtotal, $units);
}
`,
  },
  {
    path: "src/Pricing/PercentageDiscount.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Pricing;

use Acme\Billing\Money;

/**
 * Reduces a subtotal by a percentage.
 */
final class PercentageDiscount implements DiscountPolicy
{
    /** @var float */
    private $percent;

    public function __construct($percent)
    {
        $this->percent = (float) $percent;
    }

    /**
     * Fluent constructor written with late static binding so that
     * subclasses resolve to their own class.
     */
    public static function of($percent)
    {
        return new static($percent);
    }

    public function apply(Money $subtotal, $units = 1)
    {
        $base = $subtotal->multiply($units);

        return $base->subtract($base->percentage($this->percent));
    }

    public function percent()
    {
        return $this->percent;
    }
}
`,
  },
  {
    path: "src/Pricing/FlatRateDiscount.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Pricing;

use Acme\Billing\Money;

/**
 * Subtracts a flat amount per unit, floored at zero.
 */
final class FlatRateDiscount implements DiscountPolicy
{
    /** @var Money */
    private $amountPerUnit;

    public function __construct(Money $amountPerUnit)
    {
        $this->amountPerUnit = $amountPerUnit;
    }

    public function apply(Money $subtotal, $units = 1)
    {
        $deduction = $this->amountPerUnit->multiply((int) $units);
        $result = $subtotal->subtract($deduction);

        if ($result->isNegative()) {
            return new Money(0, $subtotal->currency());
        }

        return $result;
    }
}
`,
  },
  {
    path: "src/Invoice.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing;

use Acme\Billing\Support\Arrayable;
use Acme\Billing\Support\Taggable;

/**
 * An invoice aggregates priced line items for one customer.
 */
final class Invoice implements Arrayable
{
    use Taggable;

    /** @var string */
    private $number;

    /** @var Customer */
    private $customer;

    /** @var string */
    private $currency;

    /** @var float */
    private $taxRate;

    /** @var array<int, array<string, mixed>> */
    private $lines = [];

    public function __construct($number, Customer $customer, $currency = Money::DEFAULT_CURRENCY, $taxRate = '0')
    {
        $this->number = (string) $number;
        $this->customer = $customer;
        $this->currency = (string) $currency;
        $this->taxRate = (float) $taxRate;
    }

    /**
     * Adds a line item. $line must contain the keys 'product' (a Product)
     * and 'quantity' (an int); the 'note' key is ignored.
     */
    public function addLine($line)
    {
        $this->lines[] = [
            'product' => $line['product'],
            'quantity' => (int) $line['quantity'],
            'note' => $line['note'] ?? null,
        ];

        return $this;
    }

    public function addLines(array $lines)
    {
        foreach ($lines as $line) {
            $this->addLine($line);
        }

        return $this;
    }

    public function number()
    {
        return $this->number;
    }

    public function customer()
    {
        return $this->customer;
    }

    public function currency()
    {
        return $this->currency;
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function lines()
    {
        return $this->lines;
    }

    public function lineCount()
    {
        return count($this->lines);
    }

    /**
     * @return Money
     */
    public function subtotal()
    {
        $total = new Money(0, $this->currency);
        foreach ($this->lines as $line) {
            $total = $total->add(
                $line['product']->price()->multiply($line['quantity'])
            );
        }

        return $total;
    }

    /**
     * @return Money
     */
    public function tax()
    {
        return $this->subtotal()->percentage($this->taxRate);
    }

    /**
     * @return Money
     */
    public function total()
    {
        return $this->subtotal()->add($this->tax());
    }

    public function quantityForSku($sku)
    {
        $quantity = 0;
        foreach ($this->lines as $line) {
            if ($line['product']->sku() == $sku) { // loose compare on purpose
                $quantity += $line['quantity'];
            }
        }

        return $quantity;
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray()
    {
        return [
            'number' => $this->number,
            'customer_id' => $this->customer->id(),
            'currency' => $this->currency,
            'tax_rate' => (string) $this->taxRate,
            'lines' => $this->lines,
            'subtotal' => (string) $this->subtotal(),
            'tax' => (string) $this->tax(),
            'total' => (string) $this->total(),
            'tags' => $this->tags(),
        ];
    }

    public function __toString()
    {
        $rows = [];
        foreach ($this->lines as $line) {
            $rows[] = sprintf(
                '  %s x%d  %s',
                $line['product']->sku(),
                $line['quantity'],
                (string) $line['product']->price()->multiply($line['quantity'])
            );
        }

        return sprintf(
            "Invoice %s for %s\n%s\nTotal: %s",
            $this->number,
            $this->customer->name(),
            implode("\n", $rows),
            (string) $this->total()
        );
    }
}
`,
  },
  {
    path: "src/InvoiceRepository.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing;

/**
 * Stores invoices as raw associative-array rows, shaped like the legacy
 * database layer. Row keys: number, customer_id, currency, tax_rate, lines,
 * subtotal, tax, total, tags, created_at.
 */
final class InvoiceRepository implements \Countable
{
    /** @var array<string, array<string, mixed>> */
    private $rows = [];

    /**
     * @return string the invoice number just stored
     */
    public function save(Invoice $invoice, $createdAt = null)
    {
        $row = $invoice->toArray();
        $row['created_at'] = $createdAt;

        $this->rows[$invoice->number()] = $row;

        return $invoice->number();
    }

    /**
     * @param string $number
     *
     * @return Invoice[] the matching invoice, or null when not found
     */
    public function find($number)
    {
        if (!isset($this->rows[$number])) {
            return null;
        }

        return $this->hydrate($this->rows[$number]);
    }

    /**
     * @return Invoice[] all stored invoices keyed by invoice number
     */
    public function all()
    {
        $invoices = [];
        foreach ($this->rows as $number => $row) {
            $invoices[$number] = $this->hydrate($row);
        }

        return $invoices;
    }

    public function delete($number)
    {
        unset($this->rows[$number]);
    }

    public function count()
    {
        return count($this->rows);
    }

    /**
     * Sums stored invoice totals per currency.
     *
     * Totals are stored as formatted strings such as "123.45 USD", and are
     * parsed back with a float cast, which reads the leading numeric part.
     *
     * @return array<string, float>
     */
    public function totalByCurrency()
    {
        $totals = [];
        foreach ($this->rows as $number => &$row) {
            $currency = $row['currency'] ?? Money::DEFAULT_CURRENCY;
            if (!array_key_exists($currency, $totals)) {
                $totals[$currency] = 0.0;
            }
            $totals[$currency] += (float) $row['total'];
        }
        unset($row);

        return $totals;
    }

    private function hydrate(array $row)
    {
        $customer = new Customer([
            'id' => $row['customer_id'],
            'name' => $row['customer_name'] ?? 'unknown',
        ]);

        $invoice = new Invoice(
            $row['number'],
            $customer,
            $row['currency'] ?? Money::DEFAULT_CURRENCY,
            $row['tax_rate'] ?? '0'
        );

        foreach ((array) ($row['lines'] ?? []) as $line) {
            $invoice->addLine($line);
        }

        return $invoice;
    }
}
`,
  },
  {
    path: "tests/MoneyTest.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Tests;

use Acme\Billing\Money;
use PHPUnit\Framework\TestCase;

final class MoneyTest extends TestCase
{
    public function testAddsAmountsWithSameCurrency(): void
    {
        $a = new Money('12.50');
        $b = new Money(7.25);

        $this->assertSame('19.75 USD', (string) $a->add($b));
    }

    public function testParsesFormattedHumanInput(): void
    {
        $this->assertSame(1234.5, Money::parse('1,234.50')->amount());
        $this->assertSame(12.0, Money::parse(' 12 ')->amount());
    }

    public function testParseOfEmptyInputIsZero(): void
    {
        $this->assertSame(0.0, Money::parse('')->amount());
    }

    public function testMultiplyCoercesNumericStrings(): void
    {
        $this->assertSame('10.00 USD', (string) (new Money(4))->multiply('2.5'));
    }

    public function testEqualsComparesAmountsAfterFloatCoercion(): void
    {
        // The constructor casts both amounts to float, so 10 and '10.0' are
        // equal under == and under ===: the loose compare is not observable.
        $this->assertTrue((new Money(10))->equals(new Money('10.0')));
        $this->assertFalse((new Money(10, 'USD'))->equals(new Money(10, 'EUR')));
    }

    public function testSubtractMayGoNegative(): void
    {
        $result = (new Money(5))->subtract(new Money(8));

        $this->assertTrue($result->isNegative());
        $this->assertSame('-3.00 USD', (string) $result);
    }

    public function testPercentageRoundsToTwoDecimals(): void
    {
        $this->assertSame('10.13 USD', (string) (new Money(101.25))->percentage(10));
    }

    public function testRejectsCurrencyMismatch(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        (new Money(1, 'USD'))->add(new Money(1, 'EUR'));
    }
}
`,
  },
  {
    path: "tests/PricingTest.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Tests;

use Acme\Billing\Money;
use Acme\Billing\Product;
use Acme\Billing\Pricing\FlatRateDiscount;
use Acme\Billing\Pricing\PercentageDiscount;
use PHPUnit\Framework\TestCase;

final class PricingTest extends TestCase
{
    public function testPercentageDiscountFactoryReturnsOwnClass(): void
    {
        $policy = PercentageDiscount::of('20');

        $this->assertInstanceOf(PercentageDiscount::class, $policy);
        $this->assertSame(20.0, $policy->percent());
    }

    public function testPercentageDiscountAppliesToMultipliedBase(): void
    {
        $policy = PercentageDiscount::of(20);

        $this->assertSame('80.00 USD', (string) $policy->apply(new Money(50), 2));
    }

    public function testFlatRateDiscountDeductsPerUnit(): void
    {
        $policy = new FlatRateDiscount(new Money('3.50'));

        $this->assertSame('3.00 USD', (string) $policy->apply(new Money(10), 2));
    }

    public function testFlatRateDiscountFloorsAtZero(): void
    {
        $policy = new FlatRateDiscount(new Money('3.50'));

        $this->assertSame('0.00 USD', (string) $policy->apply(new Money(10), 3));
    }

    public function testProductDiscountedPriceUsesPolicy(): void
    {
        $product = new Product('SKU-1', 'Widget', 1999);
        $policy = PercentageDiscount::of(10);

        // 19.99 - 10% = 17.991, rounded to 17.99
        $this->assertSame('17.99 USD', (string) $product->discountedPrice($policy));
    }
}
`,
  },
  {
    path: "tests/InvoiceTest.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Tests;

use Acme\Billing\Customer;
use Acme\Billing\Invoice;
use Acme\Billing\Product;
use PHPUnit\Framework\TestCase;

final class InvoiceTest extends TestCase
{
    private function customer(): Customer
    {
        return new Customer(['id' => 7, 'name' => 'Alice', 'email' => 'alice@example.com']);
    }

    private function product(): Product
    {
        return (new Product('SKU-9', 'Gadget', 1999))
            ->addTags('hardware', 'sale');
    }

    public function testSubtotalTaxAndTotal(): void
    {
        $invoice = new Invoice('INV-1', $this->customer(), 'USD', '10');
        $invoice->addLine(['product' => $this->product(), 'quantity' => 2]);

        $this->assertSame('39.98 USD', (string) $invoice->subtotal());
        $this->assertSame('4.00 USD', (string) $invoice->tax());
        $this->assertSame('43.98 USD', (string) $invoice->total());
    }

    public function testAddLineCoercesQuantityFromStrings(): void
    {
        $invoice = new Invoice('INV-2', $this->customer());
        $invoice->addLine(['product' => $this->product(), 'quantity' => '3']);

        $this->assertSame(1, $invoice->lineCount());
        $this->assertSame(3, $invoice->quantityForSku('SKU-9'));
    }

    public function testQuantityForSkuComparesLoosely(): void
    {
        $numericSkuProduct = new Product('9001', 'Legacy Part', 500);
        $invoice = new Invoice('INV-3', $this->customer());
        $invoice->addLine(['product' => $numericSkuProduct, 'quantity' => 2]);

        // '9001' == 9001 is true under PHP loose comparison, and so is
        // '9001' == '9001.0' (two numeric strings compare as numbers). A
        // leading-numeric but non-numeric string such as '9001abc' compares as
        // a string and does not match. Trailing-whitespace SKUs ('9001 ') are
        // deliberately not asserted: their result differs between PHP 7 and 8.
        $this->assertSame(2, $invoice->quantityForSku(9001));
        $this->assertSame(2, $invoice->quantityForSku('9001.0'));
        $this->assertSame(0, $invoice->quantityForSku('9001abc'));
    }

    public function testToStringRendersInvoice(): void
    {
        $invoice = new Invoice('INV-4', $this->customer());
        $invoice->addLine(['product' => $this->product(), 'quantity' => 1, 'note' => 'gift']);

        $rendered = (string) $invoice;

        $this->assertStringContainsString('Invoice INV-4 for Alice', $rendered);
        $this->assertStringContainsString('SKU-9 x1', $rendered);
    }

    public function testToArrayCarriesFormattedTotals(): void
    {
        $invoice = new Invoice('INV-5', $this->customer(), 'USD', '0');
        $invoice->addLines([
            ['product' => $this->product(), 'quantity' => 1],
        ]);

        $row = $invoice->toArray();

        $this->assertSame('19.99 USD', $row['total']);
        $this->assertSame(7, $row['customer_id']);
        // toArray() reports the invoice's own tags; addLine() never copies the
        // product's tags ('hardware', 'sale') onto the invoice.
        $this->assertSame([], $row['tags']);
    }
}
`,
  },
  {
    path: "tests/InvoiceRepositoryTest.php",
    content: String.raw`
<?php

declare(strict_types=1);

namespace Acme\Billing\Tests;

use Acme\Billing\Customer;
use Acme\Billing\Invoice;
use Acme\Billing\InvoiceRepository;
use Acme\Billing\Product;
use PHPUnit\Framework\TestCase;

final class InvoiceRepositoryTest extends TestCase
{
    private function invoice($number, $customerId, $priceCents, $currency = 'USD')
    {
        $product = new Product('SKU-1', 'Widget', $priceCents, null, $currency);
        $customer = new Customer(['id' => $customerId, 'name' => 'Bob']);

        return (new Invoice($number, $customer, $currency))->addLine([
            'product' => $product,
            'quantity' => 1,
        ]);
    }

    public function testSaveAndFindRoundTrip(): void
    {
        $repo = new InvoiceRepository();

        $repo->save($this->invoice('INV-1', 7, 1999), '2026-01-15T10:30:00Z');
        $found = $repo->find('INV-1');

        $this->assertInstanceOf(Invoice::class, $found);
        $this->assertSame('19.99 USD', (string) $found->total());
        $this->assertSame(1, $found->quantityForSku('SKU-1'));
    }

    public function testHydrationLosesCustomerName(): void
    {
        $repo = new InvoiceRepository();
        $repo->save($this->invoice('INV-1', 7, 1999));

        $found = $repo->find('INV-1');

        // Storage rows carry no customer name, so hydration falls back.
        $this->assertSame('unknown', $found->customer()->name());
    }

    public function testFindMissingInvoiceReturnsNull(): void
    {
        $repo = new InvoiceRepository();

        $this->assertNull($repo->find('NOPE'));
    }

    public function testDeleteRemovesTheRow(): void
    {
        $repo = new InvoiceRepository();
        $repo->save($this->invoice('INV-1', 1, 1999));

        $repo->delete('INV-1');

        $this->assertCount(0, $repo);
        $this->assertNull($repo->find('INV-1'));
    }

    public function testAllIsKeyedByInvoiceNumber(): void
    {
        $repo = new InvoiceRepository();
        $repo->save($this->invoice('INV-1', 1, 1999));
        $repo->save($this->invoice('INV-2', 2, 2500));

        $this->assertSame(['INV-1', 'INV-2'], array_keys($repo->all()));
    }

    public function testTotalByCurrencySumsFormattedStringTotals(): void
    {
        $repo = new InvoiceRepository();
        $repo->save($this->invoice('INV-1', 1, 1999));       // "19.99 USD"
        $repo->save($this->invoice('INV-2', 1, 2500));       // "25.00 USD"
        $repo->save($this->invoice('INV-3', 2, 999, 'EUR')); // "9.99 EUR"

        $totals = $repo->totalByCurrency();

        $this->assertSame(['USD', 'EUR'], array_keys($totals));
        $this->assertEqualsWithDelta(44.99, $totals['USD'], 0.0001);
        $this->assertEqualsWithDelta(9.99, $totals['EUR'], 0.0001);
    }

    public function testIsCountable(): void
    {
        $repo = new InvoiceRepository();
        $repo->save($this->invoice('INV-1', 1, 1999));

        $this->assertCount(1, $repo);
    }
}
`,
  },
];

function normalize(raw: string): string {
  return `${raw.replace(/^\n/, "").replace(/\s+$/, "")}\n`;
}

function isCommentOnly(line: string): boolean {
  const t = line.trim();
  return (
    t.startsWith("//") || t.startsWith("/*") || t.startsWith("*") || t.startsWith("#")
  );
}

function countLines(content: string): { physical: number; nonBlank: number; code: number } {
  const lines = content.split("\n").slice(0, -1); // drop the trailing-newline stub
  let nonBlank = 0;
  let code = 0;
  for (const line of lines) {
    if (line.trim() === "") continue;
    nonBlank += 1;
    if (!isCommentOnly(line)) code += 1;
  }
  return { physical: lines.length, nonBlank, code };
}

function main(): void {
  clearOutRoot(outRoot);

  const digest = createHash("sha256");
  const width = Math.max(...FILES.map((f) => f.path.length));
  const rows: { group: string; label: string; stats: { physical: number; nonBlank: number; code: number } }[] = [];

  for (const file of FILES) {
    const content = normalize(file.content);
    const abs = join(outRoot, ...file.path.split("/"));
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content, "utf8");

    digest.update(file.path, "utf8");
    digest.update("\u0000", "utf8");
    digest.update(content, "utf8");
    digest.update("\u0000", "utf8");

    rows.push({
      group: file.path.startsWith("tests/")
        ? "tests"
        : file.path.endsWith(".php")
          ? "src"
          : "meta",
      label: `  ${file.path.padEnd(width)}  ${String(countLines(content).physical).padStart(4)} lines`,
      stats: countLines(content),
    });
  }

  const sum = (group: string, pick: (s: { physical: number; nonBlank: number; code: number }) => number): number =>
    rows.filter((r) => r.group === group).reduce((acc, r) => acc + pick(r.stats), 0);

  const fileCount = (group: string): number => rows.filter((r) => r.group === group).length;

  console.log(`fixtures/php-sample written: ${FILES.length} files`);
  for (const row of rows) console.log(row.label);
  console.log("");
  console.log(
    `src:   ${fileCount("src")} files, ` +
      `${sum("src", (s) => s.physical)} lines ` +
      `(${sum("src", (s) => s.nonBlank)} non-blank, ${sum("src", (s) => s.code)} code)`,
  );
  console.log(
    `tests: ${fileCount("tests")} files, ` +
      `${sum("tests", (s) => s.physical)} lines ` +
      `(${sum("tests", (s) => s.nonBlank)} non-blank, ${sum("tests", (s) => s.code)} code)`,
  );
  console.log("");
  console.log(`DIGEST sha256: ${digest.digest("hex")}`);
}

main();
